# Generated by Django 6.1.1 on 2026-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_sitesetting_article_likes_alter_article_is_breaking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Terms of Use, Privacy Policy, Cookies Policy, About Us', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content', models.TextField(help_text='Full legal or informative text for this page')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com', help_text='Facebook Page Link', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com', help_text='Instagram Page Link', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com', help_text='LinkedIn Page Link', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://tiktok.com', help_text='TikTok Profile Link', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='x_url',
            field=models.URLField(blank=True, default='https://x.com', help_text='X / Twitter Page Link', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, default='https://youtube.com', help_text='YouTube Channel Link', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(help_text='Brief summary shown on cards', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Upload your rectangular website logo', null=True, upload_to='site_assets/'),
        ),
    ]
