# Generated by Django 6.1.1 on 2026-10-01 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_legalpage_sitesetting_facebook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text='The instruction you ran', max_length=255)),
                ('status', models.BooleanField(default=True, help_text='True if succeeded')),
                ('response_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Command Console',
                'verbose_name_plural': 'Admin Command Console',
                'ordering': ['-timestamp'],
            },
        ),
    ]
