# Generated by Django 6.1.1 on 2026-10-04 11:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_admincommandlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your rectangular website logo', max_length=255, null=True, verbose_name='image'),
        ),
    ]
