# Generated by Django 6.1.1 on 2026-10-06 22:06

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_image_alter_sitesetting_site_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincommandlog',
            options={'ordering': ['-executed_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='legalpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
        migrations.RenameField(
            model_name='admincommandlog',
            old_name='timestamp',
            new_name='executed_at',
        ),
        migrations.RemoveField(
            model_name='admincommandlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='gmail_address',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='gmail_app_password',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Staff journalist or editorial desk attributing this story.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Description of what is happening in the photo.', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='image_credit',
            field=models.CharField(blank=True, help_text='e.g. Photo: Trending News / Reuters / AFP', max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='key_points',
            field=models.TextField(blank=True, help_text='Enter key takeaways. Put each point on a new line (they will render as BBC-style bullet highlights).'),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube embed or video URL (e.g. https://www.youtube.com/embed/VIDEO_ID).'),
        ),
        migrations.AddField(
            model_name='article',
            name='location_dateline',
            field=models.CharField(blank=True, help_text='e.g. LAGOS, ABUJA, LONDON, WASHINGTON', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description snippet. Defaults to excerpt if blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO search engine title (Google SERP limit ~60-70 chars). Defaults to title if blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft / In Review'), ('archived', 'Archived')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='sub_headline',
            field=models.CharField(blank=True, help_text='Standfirst / 1-2 sentence lead summary displayed under the title.', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated topics (e.g. Politics, Economy, Champions League, Technology).', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_notice',
            field=models.CharField(blank=True, help_text="e.g. 'Updated at 3:15 PM with police statement'", max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='contact@trendingnewsonline.org', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_description',
            field=models.TextField(blank=True, default='Your trusted source for verified news, crime alerts, and breaking stories.'),
        ),
        migrations.AlterField(
            model_name='admincommandlog',
            name='command',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Full news article body.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(help_text='Short card teaser for homepage and listing feeds.', max_length=350),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=False, help_text='Tick this to push this headline straight to the top Flash Wire marquee.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Instagram URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', verbose_name='LinkedIn URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', verbose_name='TikTok URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='x_url',
            field=models.URLField(blank=True, default='', verbose_name='X / Twitter URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, default='', verbose_name='YouTube URL'),
            preserve_default=False,
        ),
    ]
