# Generated by Django 6.1.1 on 2026-10-07 06:07

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_admincommandlog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_live_blog',
            field=models.BooleanField(default=False, help_text='Enable live rolling coverage with timestamped updates (BBC-style liveblog).'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_channel_url',
            field=models.URLField(blank=True, help_text='Direct link to your WhatsApp Channel or Community group.'),
        ),
        migrations.CreateModel(
            name='LiveBlogUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Short headline for this specific update', max_length=255)),
                ('body', models.TextField(help_text='Short update text (supports paragraphs)')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_updates', to='news.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
