# Generated by Django 6.1.1 on 2026-10-07 07:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_is_live_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign / Client Name (e.g. Zenith Bank Promo)', max_length=120)),
                ('slot', models.CharField(choices=[('top_header', 'Top Header Leaderboard (728x90 / responsive)'), ('mid_article', 'Article Body Sponsor Slot (Responsive / 728x90)'), ('sidebar', 'Sidebar Rectangle (300x250)'), ('footer', 'Bottom Footer Banner')], default='sidebar', max_length=30)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload static banner image', max_length=255, null=True, verbose_name='banner_image')),
                ('destination_url', models.URLField(blank=True, help_text='Link where the click directs to')),
                ('html_code', models.TextField(blank=True, help_text='Paste Google AdSense / HTML embed script if not using image banner')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to display or hide this banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
